use journalDB
db.CAT_people.insertOne({name: 'Nurit Alfasi', affiliation: "Ben Gurion University of the Negev", roles: ['CE']})
db.CAT_people.insertOne({name: 'David Emanuel Andersson', affiliation: "National Sun Yat-sen University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Theodore Burczak', affiliation: "Denison University", roles: ['CE']})
db.CAT_people.insertOne({name: 'William N. Butos ', affiliation: "Trinity College", roles: ['CE']})
db.CAT_people.insertOne({name: 'Per Bylund', affiliation: "Oklahoma State University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Gene Callahan', affiliation: "New York University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Chor-Yung Cheung', affiliation: "City University of Hong Kong", roles: ['CE']})
db.CAT_people.insertOne({name: 'Francesco Di Iorio', affiliation: "Nankai University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Gus diZerega', affiliation: "Taos, NM", roles: ['CE']})
db.CAT_people.insertOne({name: 'Lenore T. Ealy', affiliation: "Universidad Francisco Marroquín ", roles: ['CE']})
db.CAT_people.insertOne({name: 'Péter Érdi', affiliation: "Kalamazoo College", roles: ['CE']})
db.CAT_people.insertOne({name: 'Peter Gordon', affiliation: "University of Southern California", roles: ['CE']})
db.CAT_people.insertOne({name: 'Lauren K. Hall', affiliation: "Rochester Institute of Technology", roles: ['CE']})
db.CAT_people.insertOne({name: 'Marek Hudik', affiliation: "University of Economics Prague", roles: ['CE']})
db.CAT_people.insertOne({name: 'Sanford Ikeda', affiliation: "Purchase College, State University of New York", roles: ['CE']})
db.CAT_people.insertOne({name: 'Andrew David Irvine', affiliation: "The University of British Columbia", roles: ['CE']})
db.CAT_people.insertOne({name: 'Byron Kaldis', affiliation: "The Hellenic Open University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Peter G. Klein', affiliation: "Baylor University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Paul Lewis', affiliation: "King’s College London", roles: ['CE']})
db.CAT_people.insertOne({name: 'Ted G. Lewis', affiliation: "Technology Assessment Group, Salinas, CA", roles: ['CE']})
db.CAT_people.insertOne({name: 'Joseph Isaac Lifshitz', affiliation: "The Shalem College", roles: ['CE']})
db.CAT_people.insertOne({name: 'Jacky Mallett', affiliation: "Reykjavik University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Alberto Mingardi', affiliation: "IULM University in Milan and Istituto Bruno Leoni", roles: ['CE']})
db.CAT_people.insertOne({name: 'Stefano Moroni', affiliation: "Milan Polytechnic", roles: ['CE']})
db.CAT_people.insertOne({name: 'Edmund Neill', affiliation: "The New College of the Humanities at Northeastern University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Mikayla Novak', affiliation: "Australian National University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Christian Onof', affiliation: "Imperial College London", roles: ['CE']})
db.CAT_people.insertOne({name: 'Mark Pennington', affiliation: "King’s College London", roles: ['CE']})
db.CAT_people.insertOne({name: 'Jason Potts', affiliation: "RMIT University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Don Ross', affiliation: "University of Cape Town/Georgia State University/University College Cork", roles: ['CE']})
db.CAT_people.insertOne({name: 'Scott Scheall', affiliation: "Arizona State University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Virgil Storr', affiliation: "George Mason University", roles: ['CE']})
db.CAT_people.insertOne({name: 'Stephen Turner', affiliation: "University of South Florida", roles: ['CE']})
db.CAT_people.insertOne({name: 'Nikolai G. Wenzel', affiliation: "Fayetteville State University", roles: ['CE']})
