db.people.insertOne({name: 'Mark Adelson', position: 'Independent Consultant', affiliation: '', roles: ['EB']})
db.people.insertOne({name: 'Phil Millman', position: 'Independent Consultant', affiliation: '', roles: ['EB']})
db.people.insertOne({name: 'Will Black', position: 'Independent Consultant', affiliation: 'Black Analytics', roles: ['EB']})
db.people.insertOne({name: 'Tim Oneill', position: 'Managing Director', affiliation: 'Morningstar DBRS', roles: ['EB']})
db.people.insertOne({name: 'Nicole Byrns', position: 'Independent Consultant', affiliation: '', roles: ['EB']})
db.people.insertOne({name: 'Chun Lin', position: 'Managing Director', affiliation: 'Bank of America', roles: ['EB']})
db.people.insertOne({name: 'Debra Lofano', position: 'Finance Partner', affiliation: 'Alston & Bird', roles: ['EB']})
db.people.insertOne({name: 'Jeff Schwartz', position: 'Independent Consultant', affiliation: '', roles: ['EB']})
db.people.insertOne({name: 'David Reiss', position: 'Clinical Professor of Law', affiliation: 'Cornell Law School & Cornell Tech', roles: ['EB']})
db.people.insertOne({name: 'Caleb Adebayo', position: 'Managing Associate', affiliation: 'AO Sherman', roles: ['EB']})
db.people.insertOne({name: 'Ace Pawilkowski', position: 'Associate', affiliation: 'Dentons', roles: ['EB']})
